### ISSUE TITLE
How to replace strict() with object rest parameter

### ISSUE THREAD

**Issue by lo1tuma** [fabian-hiller/valibot#234] opened 2023-10-31 22:20 UTC
Since v0.20.0 `strict()` is deprecated and I wonder how the new rest parameter in the object schema can replace the functionality of `strict()`.

I’ve tried `never` and `undefined` but both add a new index signature to the resulting type. When I’m omitting the rest parameter completely I don’t get an error for additional properties.

```ts
const mySchema = object({ foo: string() }, never()) // { [key: string]: never; foo: string }
```

I assume the same question applies fort `strip`.

**Comment by fabian-hiller** [comment] 2023-11-01 00:33
The idea behind this is that `object` by default ignores all entries that are not defined by the `entries` argument. This behavior can be controlled with the new `rest` argument. The goal behind this was to implement `object` and `tuple` consistently and not require methods like `passthrough`, `strict` or `rest`.

 - `passthrough` can be replaced by `object({...}, unknown())`.
 - `strict` can be replaced by `object({...}, never())`.

I am aware that the `rest` argument changes the type signature. Theoretically, we could make an exception for `never` and not include it in the type signature of the schema. However, I don't know if we should do that.

Are you encountering any particular problems with the new approach?

**Comment by lo1tuma** [comment] 2023-11-01 09:27
The index signature with `never` creates an unusable type:

```ts
const mySchema = object({ foo: string() }, never());
type MyType = Output<typeof mySchema>;
const example: MyType = { foo: 'bar' };
```

For `example` I get the following TS error:

```
Type '{ foo: string; }' is not assignable to type '{ foo: string; } & Record<string, never>'. 
    Type '{ foo: string; }' is not assignable to type 'Record<string, never>'.
         Property 'foo' is incompatible with index signature.
             Type 'string' is not assignable to type 'never'. [2322]
```

**Comment by fabian-hiller** [comment] 2023-11-01 13:39
Thanks for pointing this out. I have double-checked it. When the schema is used to parse unknown data, the type definition works as intended. However, if the type signature is extracted with `Input` or `Output` to assign it to a variable, this problem occurs. Incidentally, Zod has the same problem. Currently, the best solution seems to be to make an exception for `never` and not include it in the type signature. What do you think about it?

**Comment by lo1tuma** [comment] 2023-11-01 18:03
Making an exception for `never` would work for me. I can’t see any useful scenario where an index signature with `never` would be desirable.

**Comment by fabian-hiller** [comment] 2023-11-01 18:04
Ok. I plan to publish v0.20.1 with some fixes today.

**Comment by fabian-hiller** [comment] 2023-11-03 03:21
v0.20.1 is live

**Closed** 2023-11-03 03:21 UTC
Labels: question, intended, priority
