### ISSUE TITLE
Feat: Show required field errors instead of type error

### ISSUE THREAD

**Issue by ShivamJoker** [fabian-hiller/valibot#132] opened 2023-08-31 12:25 UTC
Right now we write `string()` and we pass "data type should be string".
But how do we show the error this field is required instead of type error.

Can we modify the `flatten` method?

**Comment by Demivan** [comment] 2023-08-31 12:54
`string` method (and others) accept argument for a custom error message.

```ts
const schema = string("Field is required")
```

**Comment by ShivamJoker** [comment] 2023-08-31 13:03
Where you pass nothing or number you'll get the same error.

**Comment by Demivan** [comment] 2023-08-31 13:18
Ah, if you want to distinguish between them, you can use `nonOptional` `optional` combo :)

```ts
const schema = nonOptional(optional(string('Field is not a string')), 'Field is required')
```

**Comment by fabian-hiller** [comment] 2023-08-31 14:00
@ShivamJoker what exactly is your use case? Please give me some more details and maybe some sample code.

**Comment by ShivamJoker** [comment] 2023-09-01 10:31
@fabian-hiller I want to show the required field error in fronted which will be sent from my API.

Eg:
```ts
export const ImportListingSchmea = object({
  airbnbId: number("airbnbId must be number", [
    minValue(1, "airbnbId is too short"),
    maxValue(20, "airbnbId is too long"),
  ]),
  calendarLink: string("calendarLink must be string", [
    url("calendarLink is invalid"),
    minLength(8),
  ]),
  // s3 path for verification_document (eg. electricity bill)
  verification_document: string("verification_document must be string"),
  // price in usd
  minimumPrice: number("minimumPrice must be number"),
  maximumPrice: number("maximumPrice must be number"),
  address: string("address must be string", [
    minLength(10, "address is too short"),
  ]),
  city: string("city must be string"),
  zip: number("zip code must be string"),
});

export type ImportListingType = Output<typeof ImportListingSchmea>;

try {
  parse(ImportListingSchmea, { city: 11 });
} catch (err) {
  if (err instanceof ValiError) {
    console.log(flatten(err).nested);
  }
}
```

In the output I only see the type validation errors, not the required field errors:

```js
{
  airbnbId: [ 'airbnbId must be number' ],
  calendarLink: [ 'calendarLink must be string' ],
  verification_document: [ 'verification_document must be string' ],
  minimumPrice: [ 'minimumPrice must be number' ],
  maximumPrice: [ 'maximumPrice must be number' ],
  address: [ 'address must be string' ],
  city: [ 'city must be string' ],
  zip: [ 'zip code must be string' ]
}
```

It would be great if `flatten` or any similar method could show the required field messages, instead of type errors.

**Comment by fabian-hiller** [comment] 2023-09-01 16:34
What's wrong with changing the text in `string` to something with "required"? Or do you mean that it must not be an empty string? In that case I would use `minLength`:

```ts
const AddressSchema = string("address must be string", [minLength(1, "address is required")]);
```

**Comment by Demivan** [comment] 2023-09-01 18:38
https://github.com/fabian-hiller/valibot/issues/132#issuecomment-1701025541 does not work for you?

**Comment by ShivamJoker** [comment] 2023-09-01 18:41
Putting `nonOptional` everywhere will be too much work, how do we make everything required and few optional?

**Comment by fabian-hiller** [comment] 2023-09-01 23:10
`string` ist non optional by default. You only need `nonOptional` if you reuse a schema that is `optional`. @ShivamJoker can you send me a code example with Zod?

**Comment by fabian-hiller** [comment] 2023-09-01 23:12
Do I understand correctly that you want to have a different error message for `undefined` than for any other invalid data type?

**Comment by ShivamJoker** [comment] 2023-09-02 06:19
Yes! Exactly.

**Comment by fabian-hiller** [comment] 2023-09-02 07:35
Ok. Then @Demivan suggestion with `nonOptional` is currently the best option. Alternatively, due to the modularity of Valibot, you can also build your own `string` function that checks both separately.

**Comment by ShivamJoker** [comment] 2023-09-03 18:49
@fabian-hiller here is an example from [vinejs](https://vinejs.dev/docs/error_reporter)

This is how I define the schema:

```ts
import v from "@vinejs/vine";

const AddGroceryObj = v.array(
  v.object({
    category: v.string().toUpperCase(),
    name: v.string().toUpperCase(),
    type: v.string().toUpperCase(),
    stocks: v.number(),
    price: v.object({
      inr: v.number(),
      usd: v.number(),
    }),
  }),
);
```

And if I don't pass the key values it shows me error like this:

```json
{
  "code": "E_VALIDATION_ERROR",
  "messages": [
    {
      "field": "*.category",
      "rule": "required",
      "message": "The category field must be defined"
    },
    {
      "field": "*.name",
      "rule": "required",
      "message": "The name field must be defined"
    },
    {
      "field": "*.type",
      "rule": "required",
      "message": "The type field must be defined"
    }
  ],
  "status": 422
}
```

**Comment by fabian-hiller** [comment] 2023-09-04 12:12
Thanks for the info. You can also format the Valibot Issues so that the errors are the same or similar to Vine. A Valibot Issue contains any basic info about the problem. With `reason: "type"` and `input: undefined`, you can detect that a value for a key was not specified.

**Comment by ShivamJoker** [comment] 2023-09-05 04:00
I see but in `reason` can we make it like: field is required.

Right now I'll have to make a custom formatter which will look for the undefined and throw the required errors.

**Comment by fabian-hiller** [comment] 2023-09-05 12:56
Feel free to make a concrete proposal with sample code to change the API.

**Comment by fabian-hiller** [comment] 2023-09-17 23:15
Is there still interest in this issue? Otherwise I would close it.

**Comment by ShivamJoker** [comment] 2023-09-18 03:40
I would still want the format error function to have this.

**Comment by fabian-hiller** [comment] 2023-09-18 04:09
What is the current behavior? With `nonOptional` what you want should be possible or? I am interested in improving Valibot, but I need precise details as my time is very limited at the moment.

**Comment by chibek** [comment] 2023-11-16 11:49
Hi @fabian-hiller,
I going to try to explain my case that I think is the same that the one in this thread.


```typescript
export const authSchema = object({
  email: string([email("Please enter a valid email address")]),
  password: nonOptional(string([
    minLength(8, "Password must be at least 8 characters long"),
    maxLength(100),
  ]), "Field is required"),
});

``` 

Expected behaviour:
When my password is empty, the message showed should be "Field is required"
Actual behaviour:
When my password is empty, the message showed is "Password must be at least 8 characters long"

**Comment by fabian-hiller** [comment] 2023-11-16 15:29
`nonOptional` checks for `undefined` and not for empty strings. The schema functions validate the data type and the pipeline future details. Here is a fix:

```ts
export const authSchema = object({
  email: string([email('Please enter a valid email address')]),
  password: string([
    minLength(1, 'Field is required'),
    minLength(8, 'Password must be at least 8 characters long'),
    maxLength(100),
  ]),
});
```

**Comment by fabian-hiller** [comment] 2023-11-24 14:47
An empty string is still a string, and our schema functions only check for data types, not the actual value.

**Comment by Demivan** [comment] 2023-11-24 20:42
It is easy to create a custom function that combines `string` and `minLength(1)`

**Comment by fabian-hiller** [comment] 2024-02-28 05:04
This is now possible:

```ts
import * as v from 'valibot';

const Schema = v.string(({ input }) =>
  input === undefined ? 'This field is required' : 'This field is invalid'
);
```

You can also create your own util function:

```ts
import * as v from 'valibot';

function message({ required, invalid }: { required: string; invalid: string }) {
  return ({ input }) => (input === undefined ? required : invalid);
}

const Schema = v.string(
  message({
    required: 'This field is required',
    invalid: 'This field is invalid',
  })
);
```

**Closed by fabian-hiller** 2024-02-28 05:04 UTC
Labels: question
