### ISSUE TITLE
`NaN` bypass `number` schema and `minValue` validation

### ISSUE THREAD

**Issue by divndev** [fabian-hiller/valibot#157] opened 2023-09-13 07:44 UTC
version: 0.15.0

```js
var v = require("valibot")

console.log(
v.parse(v.coerce(v.number([v.minValue(1)]), Number), undefined)
)
```

actual result: NaN
expected result: throw error

**Comment by fabian-hiller** [comment] 2023-09-13 14:18
Thank you for creating this issue. The problem is that both checks return `false`. I will investigate this in the coming days. As a workaround you could add another check, for example `integer` validation.

```ts
const value = Number(undefined);
const boolean1 = value < 1; // false
const boolean2 = value > 1; // false
```

**Comment by fabian-hiller** [comment] 2023-09-13 22:15
The problem will be fixed in the next version

**Comment by fabian-hiller** [comment] 2023-09-16 05:22
The new version is available.

**Closed** 2023-09-16 05:23 UTC
Labels: bug, priority
