### ISSUE TITLE
Infer output for v.union + v.transform inside v.object is broken

### ISSUE THREAD

**Issue by KubaJastrz** [fabian-hiller/valibot#944] opened 2024-11-28 09:43 UTC
Code 

```tsx
import * as v from 'valibot';

const FlatSchema = v.pipe(
  v.optional(v.union([v.string(), v.number()])),
  v.transform((value) => value?.toString()),
);

// string | number | undefined
type InputFlat = v.InferInput<typeof FlatSchema>;
// string | undefined
type OutputFlat = v.InferOutput<typeof FlatSchema>;

const ObjectSchema = v.object({
  stuff: v.pipe(
    v.optional(v.union([v.string(), v.number()])),
    v.transform((value) => value?.toString()),
  ),
});

// string | number | undefined
type InputObject = v.InferInput<typeof ObjectSchema>;
// string | number | undefined -- BUG HERE
type OutputObject = v.InferOutput<typeof ObjectSchema>;
```

[Playground link](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgDFTkYBlJgAsApiGRwAvJgB0YYGGEAKenBkQwMYGzKKM0gK6strRQG09HKMFYBzRQEoANDNb6QFYVAcBde05UyMFDI7NjQIIq6ZPrC9pIAfJjRwgD80jAQfEHWdn6O9PYM9AD0xXCWOXAAPnCu7p7VcIYAJsLY1sLN9DAAngpwAJKsYPow3LySMkPYnkMjMAA8vQoQ2HDj-EKiyPEMpeXZto0tbR1dy8JwAPKj8xuTetOeNzDzS33Cq+s8myJiu4wWOx4FcKAArYRMX7bB7SCDgyEwRQAbwCHH02GwAC4ZHIFMpVKo9OpNNpSLoDEY2GYLIdcs49HUPF57L5-ITAsFQuFIiRSDE4hJEnyYmkMlkrLYHOy4P4AL6FRj7CpHGpMho1E7tVidbofQbDUagiFQ2FPKBzUbvFZrY2IgR-HZ7MoqmyNdVQY6sVrazpwAC0-rgACEAKoAcTgAAkAKIAJRjev6L3mdtNUkerBmUBTVouXzT0P+DCAA)

Affected versions: tested on 0.42.1 and 1.0.0-beta.8

**Comment by KubaJastrz** [comment] 2024-11-28 11:32
Fyi: this also fails ([playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgDFTkYBlJgAsApiGRwAvJgB0YYGGEAKenBkQwMYGzKKM0gK6strRQG09HKMFYBzRQEoANDNb6QFYVAcBde05UyMFDI7NjQIIq6ZPrC9pIAfJjRwgD80jAQfEHWdn6O9PYM9AD0xXCWOXAAPnCu7p7VcIYAJsLY1sLN9DAAngpwAJKsYPow3LySMkPYnkMjMAA8vQoQ2HDj-EKiyPEMpeXZto0tbR1dy8JwAPKj8xuTetOeNzDzS33Cq+s8myJiu4wWOx4FcKAArYRMX7bB7SCDgyEwRQAbwCHH02GwAC4ZHIFMpVKo9OpNNpSLoDEY2GYLIdcs49HUPF57L5-ITAsFQuFIiRSDE4hJEnyYmkMlkrLYHOy4P4AL6FRj7CpHGpMho1E7tVidbofQbDUagiFQ2FPKBzUbvFZrY2IgR-HZ7MoqmyNdVQY6sVrazpwAC0-rgACEAKoAcTgAAkAKIAJRjev6L3mdtNUkerBmUBTVouXzT0P+RWVdPdbmZXp9ZwDQbDkdjCaTl1zYx+hbNWeeCKhrYWqNU6MxOPzaw2Du2DDl8VMhCH2EI3gYQA))

```tsx
// string | number | undefined -- BUG HERE
type OutputFlatObject = v.InferObjectOutput<{ stuff: typeof FlatSchema }>['stuff'];
```

**Comment by fabian-hiller** [comment] 2024-11-28 17:56
I know what the problem is. Sorry for this bug. Until this is fixed, I recommend wrapping the whole `pipe` in `optional` instead of just the `union`.

```ts
const FlatSchema = v.optional(
  v.pipe(
    v.union([v.string(), v.number()]),
    v.transform((value) => value?.toString())
  )
);
```

**Comment by fabian-hiller** [comment] 2024-11-28 21:14
This should be fixed with the next release

**Comment by fabian-hiller** [comment] 2024-11-28 21:40
v1.0.0-beta.9 is available

**Closed by fabian-hiller** 2024-11-28 21:40 UTC
Labels: bug, priority
