### ISSUE TITLE
Issues importing with Node16/NodeNext moduleResolution

### ISSUE THREAD

**Issue by intrnl** [fabian-hiller/valibot#7] opened 2023-07-26 03:24 UTC
"Are the types wrong?" tool reports that `Node16`/`NodeNext` are having issues importing the package
https://arethetypeswrong.github.io/?p=valibot%400.2.0

`Bundler` is reported as using fallback condition, this is not ideal and should be fixed as well.

![image](https://github.com/fabian-hiller/valibot/assets/20620901/adb73a4a-59aa-441c-9e0d-f72e51cf3aab)

**Comment by intrnl** [comment] 2023-07-26 03:28
Related issue: https://github.com/fabian-hiller/valibot/issues/2

Ideally it shouldn't take switching between `moduleResolution` values as that affects a lot more than just making valibot work

**Comment by fabian-hiller** [comment] 2023-07-26 09:53
Thanks for the tip. Do you know what I need to do to fix this? Here is my Vite build config: https://github.com/fabian-hiller/valibot/blob/main/library/vite.config.ts

**Comment by userquin** [comment] 2023-07-26 10:16
move the types to be the first one in the package.json exports

**Comment by fabian-hiller** [comment] 2023-07-26 10:20
Have updated it. Will release a new version later.

**Comment by intrnl** [comment] 2023-07-26 10:35
Moving the types into the first condition only fixes the fallback condition warning, Node16 and NodeNext still has an issue with the types not resolving.

from my previous experience, this involves authoring the library in Node16 to begin with, I'm not too sure about other solutions

@andrewbranch heya, is there any solutions for Node16/NodeNext import problems that doesn't require writing every imports to use `.js`?

**Comment by intrnl** [comment] 2023-07-26 10:41
Making the project authored using Node16 and rewriting every single source files (346 files total) to have `.js` suffix when importing other modules fixes the issue with `Node16` at least from the ESM side, but TypeScript thinks that it's only being authored in ESM and not dual-package.

from what I can remember, the solution that another project took is to generate the TypeScript declarations twice, one for ESM, and one for CJS

![image](https://github.com/fabian-hiller/valibot/assets/20620901/c1c53e03-d1e9-4d70-b229-30831f88eaec)

**Comment by fabian-hiller** [comment] 2023-07-26 10:45
Does the problem only affect the TypeScript types of the library? If so, what does this have to do with Node? I have not had this problem yet.

In the build step, I put all the source code into a single file. Therefore there are no imports and `.js` should not be the problem. In the `dist` directory you will find the `.cjs` and `.mjs` file: https://www.npmjs.com/package/valibot?activeTab=code

**Comment by intrnl** [comment] 2023-07-26 10:47
this issue affects users that would want to use the library on their Node.js apps, whether it'd be CLI, servers etc, so unless they're using a bundler, they would be using Node16/NodeNext for module resolution if they're authoring the projects using TypeScript

**Comment by userquin** [comment] 2023-07-26 10:47
@fabian-hiller I'll try to fix it, what version of pnpm are you using? it is missing from the package.json file

**Comment by fabian-hiller** [comment] 2023-07-26 10:57
Can you check if the problem is fixed with v0.2.1?

**Comment by intrnl** [comment] 2023-07-26 10:57
assuming the "internal resolution error" is indeed because of the missing `.js` suffixes on imports, and the following description is the only way to properly solve this issue for Node16 users:

> [**Internal resolution error**](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/InternalResolutionError.md#declarations-and-javascript-match-but-are-not-checked-with-correct-settings)
> This problem can occur with `tsc` alone if the library author compiles with `--moduleResolution node` (also known as `node10`) or `bundler`, especially in combination with a package.json that has `"type": "module"`. Library authors should always compile/check with `--module node16 --moduleResolution node16` or `nodenext` (note that `module` implies the corresponding `moduleResolution` value, but not vice versa), because this is the only TypeScript mode that recognizes Node’s strict module resolution algorithm for ESM.

then the following commit fixes this: https://github.com/intrnl/valibot/commit/95db56fc02dd1d8822032de8b088a95d57a677d1

this fixes Node16 from the ESM side, fixing the CJS side would mean generating another set of declarations for CJS.

let me know if this is the only solution left that can fix this

**Comment by fabian-hiller** [comment] 2023-07-26 10:58
@userquin I use pnpm v8.6.3

**Comment by fabian-hiller** [comment] 2023-07-26 11:04
Before we add `.js` everywhere, I would like to understand how other libraries have solved this. @intrnl do you know how e.g. Zod fixed it?

**Comment by intrnl** [comment] 2023-07-26 11:08
it seems like Zod is masquerading type declarations meant for CJS as ESM

![image](https://github.com/fabian-hiller/valibot/assets/20620901/033cbea2-fb69-403d-8e25-534f03c33ba3)

**Comment by userquin** [comment] 2023-07-26 11:09
it seems you've a few more submodules and you're exporting the types from types submodule instead types module.

**Comment by fabian-hiller** [comment] 2023-07-26 11:13
@userquin what do you mean by submodule? Can you make an example and show me what do you think that we should change?

**Comment by fabian-hiller** [comment] 2023-07-26 11:16
@intrnl if I understand it correctly, the problem only affects the TypeScript types and not the JavaScript code, right? Currently I export the types under `/dist/types`. Can't we just export the types for node16 separately and reference them in the package.json? Then no change with `.js` to the source code would be necessary.

**Comment by intrnl** [comment] 2023-07-26 11:18
@fabian-hiller I've followed roughly with what Zod is doing and it seems to work well here: https://github.com/intrnl/valibot/commit/e48698af3b21f579e29ee03dd72f27a23b9ce3f3

![image](https://github.com/fabian-hiller/valibot/assets/20620901/0cb29d10-9c83-4498-9327-d976513905b9)

**Comment by fabian-hiller** [comment] 2023-07-26 11:28
@intrnl does it also work if you do not change the `tsconfig.json` and only make changes to the `package.json` and set `main` to `./dist/index.cjs`?

**Comment by fabian-hiller** [comment] 2023-07-26 11:40
@intrnl yes, but to `./dist/index.cjs`:

```json
  "main": "./dist/index.cjs",
  "module": "./dist/index.mjs",
  "types": "./dist/types/index.d.ts",
```

In my tests, the types were exactly the same. Only the JavaScript files changed from import to required.

**Comment by intrnl** [comment] 2023-07-26 11:43
yeah, I switched to a fresh branch and only changed the `main` field to `./dist/index.cjs`, the result is as above

**Comment by fabian-hiller** [comment] 2023-07-26 11:45
In the code above you wrote `.mjs` instead of `.cjs`. If you change that, does it work?

**Comment by intrnl** [comment] 2023-07-26 11:49
No, same result. I'm somewhat failing to see why this would fix it since TypeScript is only concerned about the types here, and since the `types` field is provided, it will only resolve that.

**Comment by userquin** [comment] 2023-07-26 12:17
I mean this (@intrnl can you check with attached tgz via file protocol (rename it to tgz extension) ?):

[valibot-0.2.0.zip](https://github.com/fabian-hiller/valibot/files/12172261/valibot-0.2.0.zip)

![imagen](https://github.com/fabian-hiller/valibot/assets/6311119/a438a830-ba2b-4797-bd5c-01b8ffc982f1)

**Comment by userquin** [comment] 2023-07-26 12:44
we can collapse all the submodules to just keep the index, I'm using `unbuild`, tsc used only to copy the sources

**Comment by userquin** [comment] 2023-07-26 12:47
I can send a PR if you want to take a look, I'll add instructions to move to multiple submodules or to just one.

**Comment by intrnl** [comment] 2023-07-26 13:55
> ![imagen](https://user-images.githubusercontent.com/6311119/256227073-a438a830-ba2b-4797-bd5c-01b8ffc982f1.png)

This means that for anyone creating a CJS project with Node16, they'd have to use `await import` to properly get the types of `valibot` even if there's a CJS build available

**Comment by userquin** [comment] 2023-07-26 14:16
we can add require and import custom entries, if you check the cjs files you don't need to use import nor await, we need to add the cts file(s) and add the types for require

**Comment by userquin** [comment] 2023-07-26 15:07
@intrnl something like this?

![imagen](https://github.com/fabian-hiller/valibot/assets/6311119/17e072c7-1237-49bc-9964-cfa2c80d4353)

**Comment by userquin** [comment] 2023-07-26 15:20
@intrnl PR updated if you want to build the tgz and test in your local via file or link protocol

**Comment by andrewbranch** [comment] 2023-07-26 15:54
It seems like you all got this figured out, but I actually just wrote a bit of additional documentation for TS about this yesterday that might explain what’s going on:

> ### Considerations for bundling libraries
>
> If you’re using a bundler to emit your library, then all your (non-externalized) imports will be processed by the bundler with known behavior, not by your users’ unknowable environments. In this case, you can use `"module": "esnext"` and `"moduleResolution": "bundler"`, but only with a significant caveat: you must ensure that your declaration files get bundled as well. Recall the first rule of declaration files: every declaration file represents exactly one JavaScript file. If you use `"moduleResolution": "bundler"` and use a bundler to emit an ESM bundle while using `tsc` to emit many individual declaration files, your declaration files may cause errors when consumed under `"module": "nodenext"`. For example, an input file like:
>
> ```ts
> import { Component } from "./extensionless-relative-import";
> ```
>
> will have its import erased by the JS bundler, but produce a declaration file with an identical import statement. That import statement, however, will contain an invalid module specifier in Node.js, since it’s missing a file extension. For Node.js users, TypeScript will error on the declaration file and infect types referencing `Component` with `any`, assuming the dependency will crash at runtime.

**Comment by fabian-hiller** [comment] 2023-07-27 00:50
I think I could solve the problem now quite easily by using tsup as the new build step. Thank you all for the info und help!

**Closed by fabian-hiller** 2023-07-27 00:50 UTC
Labels: bug, enhancement
