### ISSUE TITLE
Incorrect type inference in v0.21.0

### ISSUE THREAD

**Issue by Sec-ant** [fabian-hiller/valibot#266] opened 2023-11-23 08:46 UTC
Hello,

I was able to use this 👇 code to parse a string into a number in v0.20.1 and get the correct type for `n` (`number`):

```ts
const n = parse(
  transform(string(), (input) => parseInt(input, 10), [minValue(0)]),
  "1",
);
```

But when I updated to v0.21.0, the inferred type of `n` of the same code became `string | number | bigint | boolean | Date`.

I have to change it to this 👇 to fix the type.

```ts
const n = parse(
  transform(string(), (input) => parseInt(input, 10), [minValue<number, number>(0)]),
  "1",
);
```

Did I miss something?

Thanks

**Comment by fabian-hiller** [comment] 2023-11-23 15:32
We did not change anything in `transform`. However, we have made changes to the validation functions such as `minValue`. I will check if this causes the problem and if there is a solution. What you can do alternatively until this is fixed is to pass a schema with a pipe instead of just a pipe as the third argument.

```ts
const n = parse(
  transform(string(), (input) => parseInt(input, 10), number([minValue(0)])),
  '1'
);
```

**Comment by fabian-hiller** [comment] 2023-11-23 15:35
If you stick with the generics as a workaround, I recommend changing the second generic to the first argument of `minValue`:

```ts
const n = parse(
  transform(string(), (input) => parseInt(input, 10), [minValue<number, 0>(0)]),
  "1",
);
```

**Comment by Sec-ant** [comment] 2023-11-23 15:46
I can use the schema workaround for now, it helps, thanks!

**Comment by fabian-hiller** [comment] 2023-12-08 17:23
Unfortunately, I haven't found a solution other than the workaround, and I'm not sure there is one. The problem is that TypeScript no longer resolves the types correctly since the internal change from a function to an object. I'll take another look at the problem in the next few weeks.

**Comment by Sec-ant** [comment] 2023-12-11 05:15
Thanks for the effort. I'm totally fine with the workaround. But IMO if using pipes as the third argument of `transform` is an allowed usage maybe this should be addressed somewhere if not here? Is this an issue that should be raised and fixed in TypeScript? Or if there's already one where I can track?

**Comment by fabian-hiller** [comment] 2023-12-11 05:21
Yes, that is why I did not close this issue. I think it is not a TypeScript bug, just a different behavior than expected on our end. I will investigate this again in the coming weeks. If there is no solution, we could simply not allow a pipe as a third argument.

**Comment by fabian-hiller** [comment] 2024-05-22 00:20
This should no longer be a problem with the latest version.

**Closed by fabian-hiller** 2024-05-22 00:20 UTC
Labels: bug, workaround, priority
