### ISSUE TITLE
Error when building 

### ISSUE THREAD

**Issue by alphadever** [fabian-hiller/valibot#547] opened 2024-04-25 00:19 UTC
I am getting the following error when running my node project
 node_modules/valibot/dist/index.d.ts(2170,27): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,42): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,65): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,74): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,94): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,108): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2170,109): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,32): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,47): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,70): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,79): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,99): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,113): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(2197,114): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,55): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,71): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,87): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,96): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,104): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,123): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,125): error TS1434: Unexpected keyword or identifier.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,134): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3358,135): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,65): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,81): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,102): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,111): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,119): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,138): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,140): error TS1434: Unexpected keyword or identifier.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,149): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(3381,150): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,58): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,77): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,92): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,103): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,106): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,114): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,131): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,144): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,168): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,182): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5066,183): error TS1128: Declaration or statement expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,58): error TS1139: Type parameter declaration expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,77): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,92): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,103): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,106): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,114): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,131): error TS1005: ',' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,144): error TS1005: ')' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,168): error TS1109: Expression expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,182): error TS1005: ';' expected.
[tsc     ] node_modules/valibot/dist/index.d.ts(5226,183): error TS1128: Declaration or statement expected.

**Comment by fabian-hiller** [comment] 2024-04-25 02:54
Does it work with the [`skipLipCheck`](https://www.typescriptlang.org/tsconfig/#skipLibCheck) option enabled?

**Comment by TithSambath** [comment] 2024-05-04 15:31
I am facing the same thing when trying to build. it working fine though on dev

![image](https://github.com/fabian-hiller/valibot/assets/54883425/f0af1218-4296-488c-84a0-9d07be8dc7d9)

**Comment by TithSambath** [comment] 2024-05-04 15:54
After rechecking valibot doc and my `package.json` again, I saw my typescript version was below the minimal requirement specify on the doc.  

![image](https://github.com/fabian-hiller/valibot/assets/54883425/bbc57ad3-84a6-410a-892b-00b7ab5dc34a)


Upgrade typescript version >= `5.0.4` , the issue is resolve for me.

![image](https://github.com/fabian-hiller/valibot/assets/54883425/65d73fac-8024-400c-99a7-e139316bfea0)

**Comment by fabian-hiller** [comment] 2024-05-04 18:14
Are you able to upgrade?

**Comment by maranomynet** [comment] 2024-05-07 10:25
I'm seeing this in several projects using `typescript` v4 (yes, with `"skipLibCheck": true`), and upgrading them to v5+ is not easy, as it would require upgrading **several** of their dependencies by major versions.

They will be upgraded (hopefully soon) but until then we can't use `valibot`.

I've found that when writing a library it's generally best to build it with a slightly older, more widely adopted version of typescript.

**Comment by fabian-hiller** [comment] 2024-05-07 14:47
Valibot requires one or two features that were introduced with TypeScript >=v5. I do not plan to downgrade the requirement, but what I can consider is releasing a version of Valibot that supports TypeScript v4 as soon as Valibot reaches v1.

**Comment by fabian-hiller** [comment] 2024-06-25 13:43
I will close this issue, but will reopen it if there is a good reason in the future.

**Closed as completed by fabian-hiller** 2024-06-25 13:43 UTC
Labels: question

**Comment by pawan549395** [comment] 2024-12-29 06:35
i have updated the typescript version  still i m getting a same error Error - [tsc] node_modules/botframework-webchat-core/node_modules/valibot/dist/index.d.ts(2170,27): error TS1139: Type parameter declaration expected.

**Comment by fabian-hiller** [comment] 2024-12-29 16:37
What is your TypeScript version and what is the Valibot version you are using?

**Comment by pawan549395** [comment] 2024-12-29 17:54
Hi fabian-Hiller/,

Thank you so much for your reply!

I have fixed the issue no code is working fine for me.

Thanks,
Pawan Mishra
