### ISSUE TITLE
[Bug] Merge/Transform make all properties in object to optional field 

### ISSUE THREAD

**Issue by harrytran998** [fabian-hiller/valibot#40] opened 2023-08-01 15:55 UTC
Hi @fabian-hiller, I have an object like this

```
    object({
      description: optional(string()),
      isActive: optional(useDefault(boolean(), true)),
      link: string(),
      title: string(),
      type: nativeEnum(MenuType),
    })
```
But when I wrap this object with transform or merge --> All properties mark optional, might be this is an expected behavior or a bug 🤔. Hope you can check this!

**Comment by fabian-hiller** [comment] 2023-08-01 16:44
I have checked this and for me only the properties `description` and `isActive` are optional. Can you send me your whole schema code?

**Comment by harrytran998** [comment] 2023-08-02 04:05
Sure, I combine two models together

```ts
export const baseSchema = object({
  createdDate: optional(string()),
  updatedDate: optional(string()),
});
```

```ts

export const createMenuSchema = merge([
  transform(
    object({
      description: optional(string()),
      endIcon: optional(string()),
      isActive: optional(useDefault(boolean(), true)),
      link: string(),
      linkType: nativeEnum(MenuLinkType),
      location: nativeEnum(MenuLocation),
      order: number(),
      parentId: optional(string()),
      startIcon: optional(string()),
      title: string(),
      type: nativeEnum(MenuType),
    }),
    (menu) => ({ ...menu, slug: slugify(menu.title) }),
  ),
  baseSchema,
]);

export type MenuModel = Output<typeof createMenuSchema>;
```

1. All properties will mark as optional
2. The new model after transform does not contain the `slug` field  🤔

Hope you can check this.

**Comment by fabian-hiller** [comment] 2023-08-02 10:16
Thank you for the details. This is an expected behavior. Please read through issue #26 and let me know what you think.

**Comment by harrytran998** [comment] 2023-08-03 08:39
Thank you for your quick response, I am not good in technical but can contribute to you the user experience from my point of view.

1. I don't know how to execute the pipe of function in order with valibot. Might be when you execute inside to outside, the result may be correct like the expected result: Remain the object type --> transform with slug --> merge with another schema.
2. I might think this stuff is really hard technically, but merge and transform it into basic things which anyone using `zod` did. I guess Zod has a trade-off to do the complicated kinds of stuff like this about bundle size or performances. 
3. If you think this was expected behavior, I think you should talk with more people using this and Zod on their production, might you can find the solutions 😆.

**Comment by fabian-hiller** [comment] 2023-08-03 09:26
Thank you for your feedback. As far as I know, Zod does not allow to merge a transformed object and this can be technically justified. With `transform`, the object can be transformed to any other data type. For example a JSON string. If Valibot or Zod have no guarantee about the outgoing data, they must either discard the transformation like Valibot or prevent merging completely like Zod.

Furthermore, when merging, Valibot allows overwriting data types if the same key occurs in multiple objects. This is another reason why `transform` cannot be executed in this case, since otherwise incorrect data in `transform` or the pipeline is expected.

To make it short. If `merge` or another object method is applied, `transform`, as well as the pipeline must be added to the merged schema all over again. I will try to document this better in the long run.

**Comment by harrytran998** [comment] 2023-08-03 09:54
Hmm, can you suggest to me how to solve this problem with Valibot? 

Bcs after using Valibot, I use this with Zod --> It worked as I expected. The code below for you can try 😆.

```
export const createMenuSchema = z
  .object({
    description: z.string().optional(),
    endIcon: z.string().optional(),
    isActive: z.boolean().optional().default(true),
    link: z.string(),
    linkType: z.nativeEnum(MenuLinkType),
    location: z.nativeEnum(MenuLocation),
    order: z.number(),
    parentId: z.string().optional(),
    startIcon: z.string().optional(),
    title: z.string(),
    type: z.nativeEnum(MenuType),
  })
  .transform((menu) => ({ ...menu, slug: slugify(menu.title) }))
  .and(baseSchema);

export type MenuModel = z.infer<typeof createMenuSchema>;

```

**Comment by fabian-hiller** [comment] 2023-08-03 09:57
```ts
const createMenuSchema = transform(
  merge([
    object({
      description: optional(string()),
      endIcon: optional(string()),
      isActive: optional(useDefault(boolean(), true)),
      link: string(),
      linkType: nativeEnum(MenuLinkType),
      location: nativeEnum(MenuLocation),
      order: number(),
      parentId: optional(string()),
      startIcon: optional(string()),
      title: string(),
      type: nativeEnum(MenuType),
    }),
    baseSchema,
  ]),
  (menu) => ({ ...menu, slug: slugify(menu.title) })
);
```

**Comment by harrytran998** [comment] 2023-08-03 10:04
```ts
export const createMenuSchema = transform(
  merge([
    object({
      link: string(),
      title: string(),
      order: number(),
      linkType: nativeEnum(MenuLinkType),
      location: nativeEnum(MenuLocation),
      type: nativeEnum(MenuType),
      description: optional(string()),
      endIcon: optional(string()),
      isActive: optional(useDefault(boolean(), true)),
      parentId: optional(string()),
      startIcon: optional(string()),
    }),
    baseSchema,
  ]),
  (menu) => ({ ...menu, slug: slugify(menu.title) }),
);

export type MenuModel = Output<typeof createMenuSchema>;

```

![image](https://github.com/fabian-hiller/valibot/assets/24296018/22922c4a-cd4e-4ec6-a98e-ed253bb8a676)


```ts

export const tenantSchema = object({
  id: number(),
  name: string([minLength(1)]),
  description: string(),
});

export type TenantModel = Output<typeof tenantSchema>;
```

![image](https://github.com/fabian-hiller/valibot/assets/24296018/b3bf67f6-4ede-401d-915e-504503e36874)

Hmm, really weird! Now anything turns to optional(valibot v 0.8.0)

**Comment by fabian-hiller** [comment] 2023-08-03 10:13
For me your code works without problems and the types are displayed correctly. Does `strict` in the `tsconfig.json` have the value `true`?

**Comment by harrytran998** [comment] 2023-08-03 10:21
Ohhh - It worked! Thank you for your quick response! This should be in the document 😆.

**Comment by fabian-hiller** [comment] 2023-08-03 10:46
Yes, I will improve the docs here. Thank you for your feedback!

**Comment by fabian-hiller** [comment] 2023-08-04 10:14
Added the info to the docs. Thanks!

**Closed by fabian-hiller** 2023-08-04 10:14 UTC
Labels: documentation, intended
